name: Lint

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: ^8.6.12
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Run lint
              run: pnpm run lint
            - name: Run check
              run: pnpm run check
